# Haskell Stack configuration
#
# See https://docs.haskellstack.org/en/stable/yaml_configuration/

resolver: lts-11.17

packages:
    - ./library
    - ./application

nix:
    enable: true
    pure: true
    packages: []
    shell-file: stack/stack.nix

flags: {}
extra-package-dbs: []
